// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ChatAssistantVSIX
{
  internal sealed partial class Vsix
  {
    public const string Id = "ChatAssistantVSIX.9a72f873-133b-4224-b774-e6d9648c420e";
    public const string Name = "ChatAssistantVSIX";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Arman Sahakyan";
    public const string Tags = "";
  }
}
