// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ChatAssistantVSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "ChatAssistantVSIX.9a72f873-133b-4224-b774-e6d9648c420e";
        public const string Name = "PhenixCode Chat Assistant";
        public const string Description = @"Coding assistant tool for Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Arman Sahakyan";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
