// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace ChatAssistantVSIX
{
  /// <summary>
  /// Helper class that exposes all GUIDs used across VS Package.
  /// </summary>
  internal sealed partial class PackageGuids
  {
    public const string ChatAssistantVSIXString = "597d1e18-b82e-4eb7-8156-2cc5144d3f2e";
    public static Guid ChatAssistantVSIX = new Guid(ChatAssistantVSIXString);
  }
  /// <summary>
  /// Helper class that encapsulates all CommandIDs uses across VS Package.
  /// </summary>
  internal sealed partial class PackageIds
  {
    public const int MyCommand = 0x0100;
  }
}