// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ChatAssistantVSIX
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ChatAssistantVSIXString = "597d1e18-b82e-4eb7-8156-2cc5144d3f2e";
        public static Guid ChatAssistantVSIX = new Guid(ChatAssistantVSIXString);

        public const string guidPackageCmdSetString = "9f212083-1a12-464b-9bc7-852184bb8bba";
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);

        public const string guidImagesString = "4e0b36dc-6a3a-48cc-8258-ee321ebffcac";
        public static Guid guidImages = new Guid(guidImagesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
        public const int TWindowToolbar = 0x1000;
        public const int TWindowToolbarGroup1 = 0x1050;
        public const int TWindowToolbarGroup2 = 0x1051;
        public const int ButtonSettingsCommand = 0x0111;
        public const int ButtonInsertCommand = 0x0112;
        public const int cmdidRejectGhostText = 0x0113;
        public const int cmdidAcceptGhostText = 0x0114;
        public const int cmdidButtonStatsCommand = 0x0115;
        public const int bmpPicMyToolWindow = 0x0001;
    }
}
